NumPy is a powerful Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, 
along with a collection of mathematical functions to operate on these arrays efficiently.

In [4]:
import numpy as np


NumPy arrays are optimized for numerical computing and offer several advantages over Python lists, including performance, memory efficiency, and support for array-oriented operations. 

In [5]:
A = np.array([1, 2, 3, 4, 5])

A


array([1, 2, 3, 4, 5])

In [6]:
B = np.array([2,4,6,8,10])

B

array([ 2,  4,  6,  8, 10])

In [7]:
ADD= A+B
print(ADD)

SUBTRACT=A-B
print(SUBTRACT)

DIVISION=A/B
print(DIVISION)

MULTIPLICATION=A*B
print(MULTIPLICATION)

[ 3  6  9 12 15]
[-1 -2 -3 -4 -5]
[0.5 0.5 0.5 0.5 0.5]
[ 2  8 18 32 50]


In [18]:
# mean,median,sum,mininum number, maximum number

A_mean = np.mean(A)
print(A_mean)

A_med = np.median(A)
print(A_med)

A_sum= np.sum(A)
print(A_sum)

A_max = A.max()
print(A_max)

A_min= A.min()
print(A_min)

3.0
3.0
15
5
1


In [10]:
A = np.array([[1, 2, 3, 4, 5],[10,12,14,16,18]])
A

array([[ 1,  2,  3,  4,  5],
       [10, 12, 14, 16, 18]])

In [14]:
#ARRAY INDEXING

# Accessing rows
print(A[0])  

# Access element at row 0, column 3
print(A [0, 2])  

## Accessing; columns
print(A[:,4]) 

# Access elements from second row onwards, and only the first two columns
print(A[ 1:]) 

[1 2 3 4 5]
3
[ 5 18]
[[10 12 14 16 18]]


In [16]:
A = A.reshape(5,2)
A

array([[ 1,  2],
       [ 3,  4],
       [ 5, 10],
       [12, 14],
       [16, 18]])

In [17]:
import numpy as np

# Example arrays
arr1 = np.array([[2, 4, 6],
                 [8, 10, 12]])
arr2 = np.array([[1, 3, 5],
                 [7, 9, 11]])

# Merge arrays into rows
merged_rows = np.vstack((arr1, arr2))
print("Merged Rows:")
print(merged_rows)

merged_rows = A

Merged Rows:
[[ 2  4  6]
 [ 8 10 12]
 [ 1  3  5]
 [ 7  9 11]]


Universal functions (ufuncs) in NumPy are functions that operate element-wise on arrays. They provide fast, vectorized operations on arrays, allowing you to perform complex mathematical operations efficiently without the need for explicit looping in Python code. Ufuncs can operate on arrays of any size and shape, and they are implemented in compiled C code, making them much faster than equivalent operations performed in pure Python.

In [29]:
import numpy as np

# Create zeros_A array filled with zeros of length 5
zeros_A = np.zeros(5)
print(zeros_A)

# Create zeros_B array filled with zeros of shape (2, 3)
zeros_B = np.zeros((2, 3))
print(zeros_B)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [1]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [2]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
import numpy as np
# Example arrays
arr1 = np.array ([[1, 2, 3],
                 [4, 5, 6]])

print (arr1)


[[1 2 3]
 [4 5 6]]


In [4]:

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])


new_number = 20
arr1[1, 1] = new_number  

print(arr1)

[[ 1  2  3]
 [ 4 20  6]]
